name: Job Service CI

on:
  push:
    branches: ["dev"]
    paths:
      - "job_service/**"
      - ".github/workflows/job-ci.yml"
      - ".github/workflows/_java-service-ci.yml"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "job_service/**"
      - ".github/workflows/job-ci.yml"
      - ".github/workflows/_java-service-ci.yml"

jobs:
  test-job:
    uses: ./.github/workflows/_java-service-ci.yml
    with:
      service_name: job_service
      service_path: job_service
