name: User Service CI

on:
  push:
    branches: ["dev"]
    paths:
      - "user-service/**"
      - ".github/workflows/user-ci.yml"
      - ".github/workflows/_java-service-ci.yml"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "user-service/**"
      - ".github/workflows/user-ci.yml"
      - ".github/workflows/_java-service-ci.yml"

jobs:
  test-user:
    uses: ./.github/workflows/_java-service-ci.yml
    with:
      service_name: user-service
      service_path: user-service
