name: API Gateway CI

on:
  push:
    branches: ["dev"]
    paths:
      - "backend/api-gateway/**"
      - ".github/workflows/gateway-ci.yml"
      - ".github/workflows/_java-service-ci.yml"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "backend/api-gateway/**"
      - ".github/workflows/gateway-ci.yml"
      - ".github/workflows/_java-service-ci.yml"

jobs:
  test-and-build:
    uses: ./.github/workflows/_java-service-ci.yml
    with:
      service_name: api-gateway
      service_path: backend/api-gateway
